services:
  dbms:
    image: postgres:18-alpine
    container_name: dbms_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: aluno
      POSTGRES_PASSWORD: fatec
      POSTGRES_DB: crudmundo
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: